# SPDX-Liscense-Identifier: GPL-2.0-or-later
#
#
# Author: Dungru Tsai <dungru.tw@gmail.com>

obj-$(CONFIG_SANTI_UIO) += santi_uio.o

ccflags-y += -I$(src)/inc

santi_uio-y += santi_uio_main.o

include $(wildcard $(src)/*.mk)
